// SPDX-License-Identifier: LGPL-3.0-only
/*
* Author: Hao-Xin Wang <wanghaoxin1996@gmail.com>
* Creation Date: 2021-10-23.
*
* Description: Implementation of fast tensor contraction functions without tensor transposition.
*/

/**
@file contract_contiguous_axes.h
@brief Implementation of a faster tensor contraction functions without involving tensor transposition operations.

       This contraction method is defined by the following constraints:
       - The contracted indices must be continuous and ordered. Specifically, for a contraction
         defined as Contract(A, B, axes1, axes2), the axes1 indices must be in ascending order with
         a step of 1, and the same applies to axes2.
       - Periodic boundary conditions for indices are allowed. For example, if A.rank() == 5,
         axes1 can be {3, 4, 0}.

       These constraints allow the transpositions required for contraction to be realized as matrix transpositions.
*/


#ifndef QLTEN_TENSOR_MANIPULATION_CONTRACT_CONTIGUOUS_AXES_H
#define QLTEN_TENSOR_MANIPULATION_CONTRACT_CONTIGUOUS_AXES_H

#include <set>

#include "qlten/framework/bases/executor.h"
#include "qlten/qltensor_all.h"
#include "qlten/tensor_manipulation/ten_ctrct.h"  // CheckContractionIndicesMatch

namespace qlten {

/**
 * @brief Specifies which side (head or tail) of a tensor's index range carries
 *        the contracted axes in `ContractContiguousAxes`.
 *
 * Used as a strongly-typed replacement for the previous `bool a_ctrct_tail`
 * and `bool b_ctrct_head` template parameters. The mapping is asymmetric:
 *   - Position A: `Tail` <-> old `a_ctrct_tail == true`,
 *                 `Head` <-> old `a_ctrct_tail == false`.
 *   - Position B: `Head` <-> old `b_ctrct_head == true`,
 *                 `Tail` <-> old `b_ctrct_head == false`.
 */
enum class CtrctSide { Head, Tail };

/**
 * @brief Lightweight counters for contiguous contraction layout preparation.
 */
struct ContiguousContractStats {
  /// Number of transpose-prepare calls before GEMM.
  size_t transpose_prepare_calls = 0;
  /// Raw-data bytes moved by transpose prepare.
  size_t transpose_prepare_bytes = 0;
  /// Number of raw-data contraction tasks generated by block sparsity.
  size_t raw_data_contract_tasks = 0;
  /// Number of GEMM calls issued by the matrix-based executor.
  size_t gemm_calls = 0;
};

/**
 * @tparam TenElemT Type of the tensor elements.
 * @tparam QNT Type of the quantum number.
 * @tparam ASide Indicates which side (Head/Tail) of tensor A carries the contracted axes.
 * @tparam BSide Indicates which side (Head/Tail) of tensor B carries the contracted axes.
 *
 * Note:
 * - When `ASide == Tail` and `BSide == Head`, no transpose is needed for the matrix product.
 * - Otherwise, transpose the corresponding tensor(s) for the matrix product.
 * - These two parameters do not change the result of the contraction but provide hints to optimize operations and enhance performance.
 */
template<typename TenElemT, typename QNT, CtrctSide ASide, CtrctSide BSide>
class MatrixBasedTensorContractionExecutor : public Executor {
 public:
  MatrixBasedTensorContractionExecutor(
      const QLTensor<TenElemT, QNT> *,
      const QLTensor<TenElemT, QNT> *,
      const size_t a_ctrct_axes_start,
      const size_t b_ctrct_axes_start,
      const size_t ctrct_axes_size,
      QLTensor<TenElemT, QNT> *,
      ContiguousContractStats *stats = nullptr
  );

  void Execute(void) override;

 private:
  void GenerateDataBlk_();

  void TransposePrepare_();

  void ExecutePost_();//clear transpose data;

  const QLTensor<TenElemT, QNT> *pa_;
  const QLTensor<TenElemT, QNT> *pb_;
  QLTensor<TenElemT, QNT> *pc_;
  size_t a_ctrct_axes_start_; //ctrct_axes include this one
  size_t b_ctrct_axes_start_;
  size_t a_ctrct_axes_end_; //ctrct_axes do not include this one
  size_t b_ctrct_axes_end_; //ctrct_axes do not include this one
  size_t ctrct_axes_size_;

  std::vector<std::vector<size_t>> saved_axes_set_;

  // trans_critical_axe == 0 imply no transpose is need for the matrix multiplication
  // If trans_critical_axe > 0, the tensor indices from 0 to a_trans_critical_axe_ - 1
  // and from a_trans_critical_axe_ to rank - 1 will be exchanged to perform the transpose.
  size_t a_trans_critical_axe_;
  size_t b_trans_critical_axe_;

  // fermion sign which haven't been count when transpose
  // only need consider saved axes.
  std::map<size_t, int> a_trans_data_blk_idx_map_to_fermion_sign_;
  std::map<size_t, int> b_trans_data_blk_idx_map_to_fermion_sign_;

  TenElemT *a_trans_data_ = nullptr;
  //TODO: more template parameter to determine if the original data is need to save,
  // so that we can save some memory.
  TenElemT *b_trans_data_ = nullptr;
  std::vector<RawDataCtrctTask> raw_data_ctrct_tasks_;
  ContiguousContractStats *stats_;
};

/**
 * @example
 *      For the general contraction: Contract(A, B, {1,2,3},{5,6,0});
 *      a_ctrct_axes_start = 1,
 *      b_ctrct_axes_start = 5,
 *      ctrct_axes_size = 3;
 *
 *      for ASide == CtrctSide::Tail case
 *          a_trans_critical_axe_ = 4 if A.Rank()>4 or a_trans_critical_axe_ = 0 if A.Rank()==4;
 *
 *
 * @tparam TenElemT
 * @tparam QNT
 * @tparam ASide
 * @tparam BSide
 * @param pa
 * @param pb
 * @param a_ctrct_axes_start
 * @param b_ctrct_axes_start
 * @param ctrct_axes_size
 * @param pc
 *
 *  question: meaning for set status?
 */
template<typename TenElemT, typename QNT, CtrctSide ASide, CtrctSide BSide>
MatrixBasedTensorContractionExecutor<TenElemT, QNT, ASide, BSide>::MatrixBasedTensorContractionExecutor(
    const QLTensor<TenElemT, QNT> *pa,
    const QLTensor<TenElemT, QNT> *pb,
    const size_t a_ctrct_axes_start,
    const size_t b_ctrct_axes_start,
    const size_t ctrct_axes_size,
    QLTensor<TenElemT, QNT> *pc,
    ContiguousContractStats *stats
) : pa_(pa), pb_(pb), pc_(pc),
    a_ctrct_axes_start_(a_ctrct_axes_start),
    b_ctrct_axes_start_(b_ctrct_axes_start),
    a_ctrct_axes_end_((a_ctrct_axes_start + ctrct_axes_size) % (pa->Rank())),
    b_ctrct_axes_end_((b_ctrct_axes_start + ctrct_axes_size) % (pb->Rank())),
    ctrct_axes_size_(ctrct_axes_size),
    saved_axes_set_(2),
    a_trans_critical_axe_((ASide == CtrctSide::Tail) ? a_ctrct_axes_end_ : a_ctrct_axes_start),
    b_trans_critical_axe_((BSide == CtrctSide::Head) ? b_ctrct_axes_start : b_ctrct_axes_end_),
    stats_(stats) {}

template<typename TenElemT, typename QNT, CtrctSide ASide, CtrctSide BSide>
void MatrixBasedTensorContractionExecutor<TenElemT, QNT, ASide, BSide>::GenerateDataBlk_() {
  using std::vector;
  const size_t a_rank(pa_->Rank()), b_rank(pb_->Rank());
  vector<vector<size_t>> ctrct_axes_set(2);
  ctrct_axes_set[0].reserve(ctrct_axes_size_);
  ctrct_axes_set[1].reserve(ctrct_axes_size_);
  saved_axes_set_[0].reserve(pa_->Rank() - ctrct_axes_size_);
  saved_axes_set_[1].reserve(pb_->Rank() - ctrct_axes_size_);
  for (size_t i = 0; i < ctrct_axes_size_; i++) {
    ctrct_axes_set[0].push_back((a_ctrct_axes_start_ + i) % a_rank);
    ctrct_axes_set[1].push_back((b_ctrct_axes_start_ + i) % b_rank);
  }
  const size_t save_axes_size_a = a_rank - ctrct_axes_size_;
  const size_t save_axes_size_b = b_rank - ctrct_axes_size_;
  for (size_t i = 0; i < save_axes_size_a; i++) {
    saved_axes_set_[0].push_back((a_ctrct_axes_end_ + i) % a_rank);
  }
  for (size_t i = 0; i < save_axes_size_b; i++) {
    saved_axes_set_[1].push_back((b_ctrct_axes_end_ + i) % b_rank);
  }
#ifndef NDEBUG
  assert(CheckContractionIndicesMatch(pa_, pb_, ctrct_axes_set) &&
         "Contraction index mismatch! See debug output above for details.");
#endif

  TenCtrctInitResTen(pa_, pb_, saved_axes_set_, pc_);  //note the order of saved_axes_set_
  raw_data_ctrct_tasks_ = pc_->GetBlkSparDataTen().DataBlkGenForTenCtrct(
      pa_->GetBlkSparDataTen(),
      pb_->GetBlkSparDataTen(),
      ctrct_axes_set,
      saved_axes_set_
  );
  if (stats_ != nullptr) {
    stats_->raw_data_contract_tasks = raw_data_ctrct_tasks_.size();
    stats_->gemm_calls = raw_data_ctrct_tasks_.size();
  }
}

template<typename TenElemT, typename QNT, CtrctSide ASide, CtrctSide BSide>
void MatrixBasedTensorContractionExecutor<TenElemT, QNT, ASide, BSide>::TransposePrepare_() {
  using std::set;
  if (a_trans_critical_axe_ > 0) {
    const auto &a_bsdt = pa_->GetBlkSparDataTen();
    const size_t a_raw_data_size = a_bsdt.GetActualRawDataSize();
    a_trans_data_ = (TenElemT *) qlten::QLMalloc(a_raw_data_size * sizeof(TenElemT));
    set < size_t > selected_data_blk_idxs;
    for (auto &task : raw_data_ctrct_tasks_) {
      selected_data_blk_idxs.insert(task.a_blk_idx);
    }
    if (stats_ != nullptr && !selected_data_blk_idxs.empty()) {
      size_t selected_elem_count = 0;
      const auto &a_blocks = a_bsdt.GetBlkIdxDataBlkMap();
      for (const size_t blk_idx : selected_data_blk_idxs) {
        selected_elem_count += a_blocks.at(blk_idx).size;
      }
      ++stats_->transpose_prepare_calls;
      stats_->transpose_prepare_bytes +=
          2 * selected_elem_count * sizeof(TenElemT);
    }
    a_bsdt.OutOfPlaceMatrixTransposeForSelectedDataBlk(
        selected_data_blk_idxs,
        a_trans_critical_axe_,
        a_trans_data_
    );
    if constexpr (Fermionicable<QNT>::IsFermionic()) {
      a_trans_data_blk_idx_map_to_fermion_sign_ =
          a_bsdt.CountResidueFermionSignForMatBasedCtrct(saved_axes_set_[0],
                                                         a_trans_critical_axe_);
    }
  }
  if (b_trans_critical_axe_ > 0) {
    const auto &b_bsdt = pb_->GetBlkSparDataTen();
    const size_t b_raw_data_size = b_bsdt.GetActualRawDataSize();
    b_trans_data_ = (TenElemT *) qlten::QLMalloc(b_raw_data_size * sizeof(TenElemT));
    set < size_t > selected_data_blk_idxs;
    for (auto &task : raw_data_ctrct_tasks_) {
      selected_data_blk_idxs.insert(task.b_blk_idx);
    }
    if (stats_ != nullptr && !selected_data_blk_idxs.empty()) {
      size_t selected_elem_count = 0;
      const auto &b_blocks = b_bsdt.GetBlkIdxDataBlkMap();
      for (const size_t blk_idx : selected_data_blk_idxs) {
        selected_elem_count += b_blocks.at(blk_idx).size;
      }
      ++stats_->transpose_prepare_calls;
      stats_->transpose_prepare_bytes +=
          2 * selected_elem_count * sizeof(TenElemT);
    }
    b_bsdt.OutOfPlaceMatrixTransposeForSelectedDataBlk(
        selected_data_blk_idxs,
        b_trans_critical_axe_,
        b_trans_data_
    );
    if constexpr (Fermionicable<QNT>::IsFermionic()) {
      b_trans_data_blk_idx_map_to_fermion_sign_ =
          b_bsdt.CountResidueFermionSignForMatBasedCtrct(saved_axes_set_[1],
                                                         b_trans_critical_axe_);
    }
  }
}

template<typename TenElemT, typename QNT, CtrctSide ASide, CtrctSide BSide>
void MatrixBasedTensorContractionExecutor<TenElemT, QNT, ASide, BSide>::ExecutePost_() {
  qlten::QLFree(a_trans_data_);
  qlten::QLFree(b_trans_data_);
}

template<typename TenElemT, typename QNT, CtrctSide ASide, CtrctSide BSide>
void MatrixBasedTensorContractionExecutor<TenElemT, QNT, ASide, BSide>::Execute() {
#ifdef QLTEN_TIMING_MODE
  Timer gen_datablk_timer("mat_based_ctrct_gen_data_blk");
#endif
  GenerateDataBlk_();
#ifdef QLTEN_TIMING_MODE
  gen_datablk_timer.PrintElapsed();
  Timer trans_pre_timer("mat_based_ctrct_mat_transpose");
#endif

  TransposePrepare_();
#ifdef QLTEN_TIMING_MODE
  trans_pre_timer.PrintElapsed();
#endif

  const TenElemT *a_raw_data;
  const TenElemT *b_raw_data;
  if (a_trans_critical_axe_ > 0) {
    a_raw_data = a_trans_data_;
  } else {
    a_raw_data = pa_->GetBlkSparDataTen().GetActualRawDataPtr();
  }

  if (b_trans_critical_axe_ > 0) {
    b_raw_data = b_trans_data_;
  } else {
    b_raw_data = pb_->GetBlkSparDataTen().GetActualRawDataPtr();
  }
  auto &bsdt_c = pc_->GetBlkSparDataTen();
#ifdef QLTEN_TIMING_MODE
  Timer contract_according_task_timer("mat_based_ctrct_do_task");
#endif

  bsdt_c.template CtrctAccordingTask<
      ASide == CtrctSide::Tail,
      BSide == CtrctSide::Head
  >(
      a_raw_data,
      b_raw_data,
      raw_data_ctrct_tasks_,
      a_trans_data_blk_idx_map_to_fermion_sign_,
      b_trans_data_blk_idx_map_to_fermion_sign_
  );
#ifdef QLTEN_TIMING_MODE
  contract_according_task_timer.PrintElapsed();
#endif
  ExecutePost_();
}

/**
 * @brief Preferred contiguous-axes tensor contraction API.
 *
 * Drop-in alternative to `Contract<T, QNT, bool, bool>` with a self-documenting
 * `CtrctSide` template parameter pair. Defaults `Tail, Head` match the
 * dominant call pattern (the legacy `<..., true, true>` case).
 *
 * @tparam ASide On tensor A, which side of the index range carries the
 *               contracted axes (`Tail` or `Head`).
 * @tparam BSide On tensor B, same meaning.
 */
template<typename TenElemT, typename QNT,
         CtrctSide ASide = CtrctSide::Tail,
         CtrctSide BSide = CtrctSide::Head>
void ContractContiguousAxes(
    const QLTensor<TenElemT, QNT> &pa,
    const QLTensor<TenElemT, QNT> &pb,
    const size_t a_ctrct_axes_start,
    const size_t b_ctrct_axes_start,
    const size_t ctrct_axes_size,
    QLTensor<TenElemT, QNT> &pc,
    ContiguousContractStats *stats = nullptr
) {
  if (stats != nullptr) {
    *stats = ContiguousContractStats{};
  }
  auto executor = MatrixBasedTensorContractionExecutor<TenElemT, QNT, ASide, BSide>(
      &pa, &pb, a_ctrct_axes_start, b_ctrct_axes_start, ctrct_axes_size, &pc, stats
  );
  executor.Execute();
}

// Note: `TenElemT` is unused in the body but kept in the template parameter list
// so callers can write `ContractContiguousAxes<QLTEN_Complex, QNT, ...>(...)`
// symmetrically with the same-precision overload. This matches the existing
// pattern of the legacy mixed-precision `Contract` overloads further down in
// this file.
template<typename TenElemT, typename QNT,
         CtrctSide ASide = CtrctSide::Tail,
         CtrctSide BSide = CtrctSide::Head>
void ContractContiguousAxes(
    const QLTensor<QLTEN_Complex, QNT> &pa,
    const QLTensor<QLTEN_Double, QNT> &pb,
    const size_t a_ctrct_axes_start,
    const size_t b_ctrct_axes_start,
    const size_t ctrct_axes_size,
    QLTensor<QLTEN_Complex, QNT> &pc
) {
  auto pb_complex = ToComplex(pb);
  ContractContiguousAxes<QLTEN_Complex, QNT, ASide, BSide>(
      pa, pb_complex,
      a_ctrct_axes_start, b_ctrct_axes_start, ctrct_axes_size, pc);
}

template<typename TenElemT, typename QNT,
         CtrctSide ASide = CtrctSide::Tail,
         CtrctSide BSide = CtrctSide::Head>
void ContractContiguousAxes(
    const QLTensor<QLTEN_Double, QNT> &pa,
    const QLTensor<QLTEN_Complex, QNT> &pb,
    const size_t a_ctrct_axes_start,
    const size_t b_ctrct_axes_start,
    const size_t ctrct_axes_size,
    QLTensor<QLTEN_Complex, QNT> &pc
) {
  auto pa_complex = ToComplex(pa);
  ContractContiguousAxes<QLTEN_Complex, QNT, ASide, BSide>(
      pa_complex, pb,
      a_ctrct_axes_start, b_ctrct_axes_start, ctrct_axes_size, pc);
}

/**
 * @brief Contract tail axes of A with head axes of B through the no-transpose
 *        contiguous-axes path.
 *
 * This wrapper names the dominant materialized rank-4 contraction pattern
 * explicitly.  It dispatches to `ContractContiguousAxes<Tail, Head>`, whose
 * matrix-based executor uses the original block data without transpose prepare.
 */
template<typename TenElemT, typename QNT>
void ContractTailHeadContiguous(
    const QLTensor<TenElemT, QNT> &pa,
    const QLTensor<TenElemT, QNT> &pb,
    const size_t a_ctrct_axes_start,
    const size_t b_ctrct_axes_start,
    const size_t ctrct_axes_size,
    QLTensor<TenElemT, QNT> &pc,
    ContiguousContractStats *stats = nullptr
) {
  ContractContiguousAxes<TenElemT, QNT, CtrctSide::Tail, CtrctSide::Head>(
      pa, pb,
      a_ctrct_axes_start, b_ctrct_axes_start, ctrct_axes_size, pc, stats);
}

/**
 *
 * @tparam TenElemT
 * @tparam QNT
 * @tparam a_ctrct_use_tail
 * @tparam b_ctrct_use_head
 * @param pa
 * @param pb
 * @param a_ctrct_axes_start
 * @param a_ctrct_axes_size
 * @param b_ctrct_axes_start
 * @param b_ctrct_axes_size
 * @param pc
 */
template<typename TenElemT, typename QNT, bool a_ctrct_tail = true, bool b_ctrct_head = true>
void Contract(
    const QLTensor<TenElemT, QNT> &pa, //use ref to make sure it is not a null pointer
    const QLTensor<TenElemT, QNT> &pb, //TODO: unify the style of code
    const size_t a_ctrct_axes_start,
    const size_t b_ctrct_axes_start,
    const size_t ctrct_axes_size,
    QLTensor<TenElemT, QNT> &pc
) {
  constexpr CtrctSide ASide = a_ctrct_tail ? CtrctSide::Tail : CtrctSide::Head;
  constexpr CtrctSide BSide = b_ctrct_head ? CtrctSide::Head : CtrctSide::Tail;
  ContractContiguousAxes<TenElemT, QNT, ASide, BSide>(
      pa, pb,
      a_ctrct_axes_start, b_ctrct_axes_start, ctrct_axes_size, pc);
}

template<typename TenElemT, typename QNT, bool a_ctrct_tail = true, bool b_ctrct_head = true>
void Contract(
    const QLTensor<QLTEN_Complex, QNT> &pa, //use ref to make sure it is not a null pointer
    const QLTensor<QLTEN_Double, QNT> &pb, //TODO: unify the style of code
    const size_t a_ctrct_axes_start,
    const size_t b_ctrct_axes_start,
    const size_t ctrct_axes_size,
    QLTensor<QLTEN_Complex, QNT> &pc
) {
  auto pb_complex = ToComplex(pb);
  Contract<QLTEN_Complex, QNT, a_ctrct_tail, b_ctrct_head>(pa,
                                                           pb_complex,
                                                           a_ctrct_axes_start,
                                                           b_ctrct_axes_start,
                                                           ctrct_axes_size,
                                                           pc);
}

template<typename TenElemT, typename QNT, bool a_ctrct_tail = true, bool b_ctrct_head = true>
void Contract(
    const QLTensor<QLTEN_Double, QNT> &pa, //use ref to make sure it is not a null pointer
    const QLTensor<QLTEN_Complex, QNT> &pb, //TODO: unify the style of code
    const size_t a_ctrct_axes_start,
    const size_t b_ctrct_axes_start,
    const size_t ctrct_axes_size,
    QLTensor<QLTEN_Complex, QNT> &pc
) {
  auto pa_complex = ToComplex(pa);
  Contract<QLTEN_Complex, QNT, a_ctrct_tail, b_ctrct_head>(pa_complex,
                                                           pb,
                                                           a_ctrct_axes_start,
                                                           b_ctrct_axes_start,
                                                           ctrct_axes_size,
                                                           pc);
}
}//qlten



#endif //QLTEN_TENSOR_MANIPULATION_CONTRACT_CONTIGUOUS_AXES_H
